#!/usr/bin/env python3
"""Compile src/plat/win32/relic_icon.txt into src/plat/macppc/icons.r.

Host-side asset generator: run once whenever relic_icon.txt changes and
commit the resulting icons.r. Rez compiles it into the app's resource
fork via add_application() in build/macppc/CMakeLists.txt.

    python3 tools/gen_macppc_icons.py

Emits the classic Mac OS Finder icon plumbing:
  - icon family ID 128: ICN#/icl4/icl8 (32x32) + ics#/ics4/ics8 (16x16)
  - BNDL/FREF/signature resources binding the family to creator 'RLiC'
    (the creator is set on the file by Rez -c, see CMakeLists.txt)

Color notes: icl4 uses the fixed Mac 4-bit CLUT (silver -> light gray,
navy -> blue). icl8 quantizes each channel to the 8-bit system palette's
6-level color cube (silver C0C0C0 -> CCCCCC, navy 000080 -> 000099);
black is special-cased to index 255 per the real CLUT layout. The 1-bit
ICN#/ics# render outline + eyes + mouth black on a white body.
"""

import os

import pixmap

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "src", "plat", "win32", "relic_icon.txt")
OUT = os.path.join(ROOT, "src", "plat", "macppc", "icons.r")

CREATOR = "RLiC"

# Legend char -> index in the fixed Mac 4-bit CLUT.
# CLUT4: 0 white, 1 yellow, 2 orange, 3 red, 4 magenta, 5 purple, 6 blue,
# 7 cyan, 8 green, 9 dk green, 10 brown, 11 tan, 12 lt gray, 13 md gray,
# 14 dk gray, 15 black.
CLUT4 = {
    "W": 0, "Y": 1, "R": 3, "M": 4, "B": 6, "N": 6, "C": 7,
    "T": 9, "S": 12, "G": 13, "#": 15, ".": 0,
}


def clut8(char):
    """Legend char -> index in the Mac 8-bit system palette."""
    if char == ".":
        return 0                              # white; AND mask hides it
    r, g, b = pixmap.RGB[char]
    if (r, g, b) == (0, 0, 0):
        return 255                            # black lives at 255, not in the cube
    lv = lambda v: int(round(v / 51.0))       # quantize to 6-level cube
    return (5 - lv(r)) * 36 + (5 - lv(g)) * 6 + (5 - lv(b))


def pack_bits(rows, predicate):
    """1 bit per pixel, MSB first, rows top-down (Mac icons are top-down)."""
    out = bytearray()
    for row in rows:
        acc, n = 0, 0
        for c in row:
            acc = (acc << 1) | (1 if predicate(c) else 0)
            n += 1
            if n == 8:
                out.append(acc)
                acc, n = 0, 0
    return bytes(out)


def pack_nibbles(rows, table):
    out = bytearray()
    for row in rows:
        for i in range(0, len(row), 2):
            out.append((table[row[i]] << 4) | table[row[i + 1]])
    return bytes(out)


def pack_bytes(rows):
    return bytes(clut8(c) for row in rows for c in row)


def rez_data(rtype, rid, blob, comment):
    lines = ["/* %s */" % comment, "data '%s' (%d) {" % (rtype, rid)]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append('\t$"%s"' % chunk.hex().upper())
    lines.append("};\n")
    return "\n".join(lines)


def main():
    big = pixmap.parse_block(SRC, "ICON32", 32, 32)
    small = pixmap.parse_block(SRC, "ICON16", 16, 16)

    is_black = lambda c: c in "#N"            # outline + eyes/mouth in 1-bit
    is_solid = lambda c: c != "."

    parts = ["""\
/* Generated by tools/gen_macppc_icons.py from src/plat/win32/relic_icon.txt
 * -- do not edit by hand. Finder icon family + bundle for Relic.
 * The creator code here must match CREATOR in build/macppc/CMakeLists.txt. */

#include "Types.r"

/* Signature resource: marks the bundle owner. */
type '%(cr)s' as 'STR ';
resource '%(cr)s' (0, purgeable) {
\t"Relic for classic Mac OS"
};

/* Bundle: tells Finder which icon family belongs to this creator. */
resource 'BNDL' (128, purgeable) {
\t'%(cr)s', 0,
\t{
\t\t'ICN#', { 0, 128 },
\t\t'FREF', { 0, 128 }
\t}
};

resource 'FREF' (128, purgeable) {
\t'APPL', 0, ""
};
""" % {"cr": CREATOR}]

    parts.append(rez_data("ICN#", 128,
                          pack_bits(big, is_black) + pack_bits(big, is_solid),
                          "32x32 1-bit icon + mask"))
    parts.append(rez_data("icl4", 128, pack_nibbles(big, CLUT4),
                          "32x32 4-bit icon"))
    parts.append(rez_data("icl8", 128, pack_bytes(big),
                          "32x32 8-bit icon"))
    parts.append(rez_data("ics#", 128,
                          pack_bits(small, is_black) + pack_bits(small, is_solid),
                          "16x16 1-bit icon + mask"))
    parts.append(rez_data("ics4", 128, pack_nibbles(small, CLUT4),
                          "16x16 4-bit icon"))
    parts.append(rez_data("ics8", 128, pack_bytes(small),
                          "16x16 8-bit icon"))

    with open(OUT, "w") as f:
        f.write("\n".join(parts))

    sizes = {"ICN#": 256, "icl4": 512, "icl8": 1024,
             "ics#": 64, "ics4": 128, "ics8": 256}
    print("wrote %s (icon family: %s)" % (
        os.path.relpath(OUT, ROOT),
        ", ".join("%s=%dB" % kv for kv in sorted(sizes.items()))))


if __name__ == "__main__":
    main()
