#!/bin/sh
# One-time xemu setup for the xbox target.
#   tools/setup_xbox.sh                  # use existing assets, write toml
#   tools/setup_xbox.sh BIOS HDD         # adopt user-supplied images
#   XBOX_BIOS=... XBOX_HDD=... XBOX_MCPX=... tools/setup_xbox.sh
#
# BIOS (1 MB flash) + HDD (qcow2) must come from your own console -- xemu's
# first-launch GUI walks through dumping them. Nothing copyrighted ships here.
#
# xemu hard-codes its config dir to ~/Library/Application Support/xemu/xemu/
# so the toml is written THERE; any existing file is backed up to
# xemu.toml.relic-bak and restored by `tools/run_xbox.sh --restore`.
set -e
cd "$(dirname "$0")/.."
ROOT=$(pwd)

# Emulator assets are per-user machine state, not per-branch: stage them in
# the main repo and symlink each worktree at them (saves ~1 GB per worktree
# and survives worktree deletion).
REAL_ROOT=$(git -C "$ROOT" rev-parse --git-common-dir 2>/dev/null | xargs -I{} dirname {} 2>/dev/null)
if [ -n "$REAL_ROOT" ] && [ "$REAL_ROOT" != "$ROOT" ] && [ -d "$REAL_ROOT" ]; then
  EMU=$REAL_ROOT/emu/xbox
else
  EMU=$ROOT/emu/xbox
fi
mkdir -p "$EMU"

sync_worktree_symlinks() {
  [ "$EMU" = "$ROOT/emu/xbox" ] && return 0
  mkdir -p "$ROOT/emu/xbox"
  for dst in bios.bin flash.bin hdd.qcow2 xemu.app xemu.toml eeprom.bin; do
    if [ -e "$EMU/$dst" ] && [ ! -e "$ROOT/emu/xbox/$dst" ]; then
      ln -s "$EMU/$dst" "$ROOT/emu/xbox/$dst"
    fi
  done
  return 0
}
sync_worktree_symlinks

BIOS_ARG=${1:-${XBOX_BIOS:-}}
HDD_ARG=${2:-${XBOX_HDD:-}}
MCPX_ARG=${XBOX_MCPX:-}

XEMU_DIR="$HOME/Library/Application Support/xemu/xemu"

ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()  { printf '  \033[31m✗\033[0m %s\n' "$*"; exit 1; }

echo "Setting up xemu assets in $EMU/"

[ -d "$EMU/xemu.app" ] || die "xemu.app missing under $EMU/. Drop the macOS xemu build there
     (https://xemu.app/docs/download/) so the launch path stays inside the repo."
ok "xemu.app     ($EMU/xemu.app)"

# --- BIOS / flash ROM / HDD ------------------------------------------------
adopt() {
  src=$1; dst=$2; label=$3
  if [ -z "$src" ] && [ -f "$dst" ]; then
    ok "$label  (already present)"
    return
  fi
  [ -n "$src" ] || die "$label  missing — pass path or set env var (see header)"
  [ -f "$src" ] || die "$label  not found: $src"
  src=$(cd "$(dirname "$src")" && pwd)/$(basename "$src")
  rm -f "$dst"
  cp -c "$src" "$dst" 2>/dev/null || cp "$src" "$dst"
  ok "$label  ← $src"
}

# xemu's toml calls MCPX "bootrom_path" and the 1 MB flash "flashrom_path"
# -- we name staged files to match: bios.bin == MCPX, flash.bin == BIOS.
adopt "$MCPX_ARG" "$EMU/bios.bin"   "bios.bin    (MCPX)"
adopt "$BIOS_ARG" "$EMU/flash.bin"  "flash.bin   (1 MB BIOS)"
adopt "$HDD_ARG"  "$EMU/hdd.qcow2"  "hdd.qcow2  "

# --- write the xemu config (in xemu's hard-coded dir, with backup) --------
mkdir -p "$XEMU_DIR"
if [ -f "$XEMU_DIR/xemu.toml" ] && [ ! -f "$XEMU_DIR/xemu.toml.relic-bak" ]; then
  cp "$XEMU_DIR/xemu.toml" "$XEMU_DIR/xemu.toml.relic-bak"
  ok "backed up    → $XEMU_DIR/xemu.toml.relic-bak"
fi

# eeprom: leave xemu's existing one in place if present, else let xemu auto-create.
EEPROM="$XEMU_DIR/eeprom.bin"
if [ ! -f "$EEPROM" ]; then
  warn "eeprom.bin   (xemu will auto-create on first boot)"
fi

cat > "$XEMU_DIR/xemu.toml" <<EOF
# Generated by relic tools/setup_xbox.sh.
# A backup of any prior config lives at xemu.toml.relic-bak.
# Restore with: tools/run_xbox.sh --restore

[general]
show_welcome = false

[sys]
mem_limit = '64'                # original Xbox RAM
avpack    = 'hdtv'

[net]
enable = true

[sys.files]
bootrom_path  = '$EMU/bios.bin'
flashrom_path = '$EMU/flash.bin'
eeprom_path   = '$EEPROM'
hdd_path      = '$EMU/hdd.qcow2'
# dvd_path is rewritten per launch by tools/run_xbox.sh
dvd_path      = ''
EOF
ok "xemu.toml    ($XEMU_DIR/xemu.toml)"

sync_worktree_symlinks   # re-run now that adopted files may exist
[ "$EMU" = "$ROOT/emu/xbox" ] || ok "worktree     symlinks → $EMU/"

echo
echo "Ready. Next:"
echo "    make run-xbox          # build .xbe, boot xemu with networking"
