#!/bin/sh
# One-time Dolphin setup for the wii target.
#   tools/setup_wii.sh                # use existing assets, write config
#   WII_NAND=~/path/to/nand  tools/setup_wii.sh   # adopt a NAND dump (optional)
#
# Unlike xemu, Dolphin needs no copyrighted BIOS to boot homebrew .dol files;
# this script only stages the emulator app, points its virtual SD root at our
# build output, and enables USB-keyboard passthrough + the Broadband Adapter.
#
# Dolphin's user dir is ~/Library/Application Support/Dolphin on macOS. Any
# existing Dolphin.ini is backed up to Dolphin.ini.relic-bak and restored by
# `tools/run_wii.sh --restore`.
set -e
cd "$(dirname "$0")/.."
ROOT=$(pwd)

REAL_ROOT=$(cd "$ROOT" && git rev-parse --path-format=absolute --git-common-dir 2>/dev/null \
             | xargs -I{} dirname {} 2>/dev/null)
if [ -n "$REAL_ROOT" ] && [ "$REAL_ROOT" != "$ROOT" ] && [ -d "$REAL_ROOT" ]; then
  EMU=$REAL_ROOT/emu/wii
else
  EMU=$ROOT/emu/wii
fi
mkdir -p "$EMU"

sync_worktree_symlinks() {
  [ "$EMU" = "$ROOT/emu/wii" ] && return 0
  mkdir -p "$ROOT/emu/wii"
  for dst in Dolphin.app nand; do
    if [ -e "$EMU/$dst" ] && [ ! -e "$ROOT/emu/wii/$dst" ]; then
      ln -s "$EMU/$dst" "$ROOT/emu/wii/$dst"
    fi
  done
  return 0
}
sync_worktree_symlinks

DOLPHIN_DIR="$HOME/Library/Application Support/Dolphin"
INI="$DOLPHIN_DIR/Config/Dolphin.ini"

ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()  { printf '  \033[31m✗\033[0m %s\n' "$*"; exit 1; }

echo "Setting up Dolphin assets in $EMU/"

[ -d "$EMU/Dolphin.app" ] || die "Dolphin.app missing under $EMU/. Drop the macOS Dolphin build there
     (https://dolphin-emu.org/download/) so the launch path stays inside the repo."
ok "Dolphin.app  ($EMU/Dolphin.app)"

if [ -n "$WII_NAND" ]; then
  [ -d "$WII_NAND" ] || die "WII_NAND not a directory: $WII_NAND"
  rm -rf "$EMU/nand"
  cp -R "$WII_NAND" "$EMU/nand"
  ok "nand/        ← $WII_NAND"
elif [ -d "$EMU/nand" ]; then
  ok "nand/        (already present)"
else
  warn "nand/        (none — Dolphin will synthesise a blank one; homebrew is fine)"
fi

mkdir -p "$DOLPHIN_DIR/Config"
if [ -f "$INI" ] && [ ! -f "$INI.relic-bak" ]; then
  cp "$INI" "$INI.relic-bak"
  ok "backed up    → $INI.relic-bak"
fi

# Only the keys we need; Dolphin merges with its own defaults on first run.
# WiiSDCardAllowWrites + WiiSDCardEnableFolderSync makes Dolphin mirror
# dist/wii/sd/ straight onto the virtual SD without an .img round-trip.
SD_SYNC="$ROOT/dist/wii/sd"
mkdir -p "$SD_SYNC"
cat > "$INI" <<EOF
# Generated by relic tools/setup_wii.sh.
# A backup of any prior config lives at Dolphin.ini.relic-bak.
# Restore with: tools/run_wii.sh --restore

[Core]
SerialPort1 = 10
SIDevice0 = 7
WiiSDCard = True
WiiSDCardAllowWrites = True
WiiSDCardEnableFolderSync = True
WiiKeyboard = True

[General]
WiiSDCardSyncFolder = $SD_SYNC/
EOF
ok "Dolphin.ini  ($INI)"

sync_worktree_symlinks
[ "$EMU" = "$ROOT/emu/wii" ] || ok "worktree     symlinks → $EMU/"

echo
echo "Ready. Next:"
echo "    make run-wii           # build .dol, stage SD, boot Dolphin"
